### PR TITLE
Wl merge

### PR DESCRIPTION
**Pull request by uvms**

### CODE REVIEW

**Comment by gkgeorgiev** [comment]
This week we will create a bru-dev brunch with the latest of our usm4uvms which is compatible with the latest of USM 1.6.1

**Comment by uvms** [comment]
Thats great! Have a look at this document for branching strategy https://focusfish.atlassian.net/wiki/display/FOC/GITHUB+branching
This is not in effect yet, so just create a bru-dev from dev and add your stuff. If it works fine, merge it back to dev.

**Comment by gkgeorgiev** [comment]
That's something new ... so correct me if I've understood it wrongly, but each team has it's own dev, which should be a brunch of common dev and which is the development of Master.
Right?

**Comment by uvms** [comment]
No, the idea is that anyone can work in any module, so for every feature there will be a branch taken from dev and when that feature is done, a pull request is openend and eventually merged into dev. When it is time for release dev is merged into master and released.

I guess you will be receiving some form of information on this more officially sometime soon. As I said, this is not in effect yet, so for now branch as you feel is needed to get your stuff into dev.

**Pull request merged**
